import Navbar from './navbar'
import Footer from './footer'
import {ClerkProvider} from '@clerk/nextjs'
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'KSMS',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
    <header>
      <Navbar />
      <ToastContainer 
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme = "light"
    />
    </header>
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
    </ClerkProvider>
    </>
  )
}
